---
jobs:
- name: merge-upstream
  public: true
  plan:
    - get: uaa-release-fork
    - get: uaa-release-upstream
      trigger: true
    - task: merge-upstream
      config:
        platform: linux
        image: docker:///18fgsa/concourse-task
        inputs:
        - name: uaa-release-fork
        - name: uaa-release-upstream
        run:
          path: ./merge_upstream.sh
          args: ["../uaa-release-upstream"]
          dir: uaa-release-fork
      on_failure:
        put: slack
        params:
          channel: {{slack-channel}}
          username: {{slack-username}}
          icon_url: {{slack-icon-url}}
          text: ':x: uaa-release upstream conflicts with our fork'

resources:
- name: uaa-release-fork
  type: git
  source:
    uri: https://github.com/cnelson/uaa-release
    branch: master
- name: uaa-release-upstream
  type: git
  source:
    uri: https://github.com/cloudfoundry/uaa-release
    branch: master
- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource